# Autogenerated wrapper script for AmazonCACerts_jll for any
export amazon_ca_root_certificate, combined_ca_root_certificates, rds_ca_root_certificate

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `amazon_ca_root_certificate`
const amazon_ca_root_certificate_splitpath = ["share", "AmazonRootCA1.pem"]

# This will be filled out by __init__() for all products, as it must be done at runtime
amazon_ca_root_certificate_path = ""

# amazon_ca_root_certificate-specific global declaration
# This will be filled out by __init__()
amazon_ca_root_certificate = ""


# Relative path to `combined_ca_root_certificates`
const combined_ca_root_certificates_splitpath = ["share", "combined-amazon-root-ca.pem"]

# This will be filled out by __init__() for all products, as it must be done at runtime
combined_ca_root_certificates_path = ""

# combined_ca_root_certificates-specific global declaration
# This will be filled out by __init__()
combined_ca_root_certificates = ""


# Relative path to `rds_ca_root_certificate`
const rds_ca_root_certificate_splitpath = ["share", "rds-ca-2019-root.pem"]

# This will be filled out by __init__() for all products, as it must be done at runtime
rds_ca_root_certificate_path = ""

# rds_ca_root_certificate-specific global declaration
# This will be filled out by __init__()
rds_ca_root_certificate = ""


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"AmazonCACerts")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global amazon_ca_root_certificate_path = normpath(joinpath(artifact_dir, amazon_ca_root_certificate_splitpath...))

    global amazon_ca_root_certificate = amazon_ca_root_certificate_path
    global combined_ca_root_certificates_path = normpath(joinpath(artifact_dir, combined_ca_root_certificates_splitpath...))

    global combined_ca_root_certificates = combined_ca_root_certificates_path
    global rds_ca_root_certificate_path = normpath(joinpath(artifact_dir, rds_ca_root_certificate_splitpath...))

    global rds_ca_root_certificate = rds_ca_root_certificate_path
    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

